name: Deploy Workflow
on:
  push:
    tags:
      - "*"
jobs:
  build-linux:
    name: Build Linux
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - name: Check architecture
        run: |
          uname -a
          find $(rustc --print sysroot) -name 'libstd-*.rlib' | sed -ne 's:^.*/\([^/]*\)/lib/libstd-[^/]*.rlib:\1:p'
      - name: apt
        run: sudo apt update && sudo apt install -yq pkg-config libdbus-1-dev libssl-dev golang clang
      - name: Checkout code from repository
        uses: actions/checkout@v4
      - name: Build Base
        run: cargo build --release
      - name: Transform filenames
        run: mv target/release/proton-drive-bridge proton-drive-bridge
      - name: build archive
        run: |
            tar cvfz proton-drive-bridge-linux-x64.tgz proton-drive-bridge users.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proton-drive-bridge-linux
          path: proton-drive-bridge-linux-x64.tgz
          retention-days: 5
  build-windows:
    name: Build Windows
    timeout-minutes: 90
    runs-on: windows-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: build archive
        run: |
          copy users.json .\target\release
          cd target\release
          7z a -tzip proton-drive-bridge-windows-x64.zip *.exe *.json *.dll
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proton-drive-bridge-windows
          path: target/release/proton-drive-bridge-windows-x64.zip
          retention-days: 5
  build-osx-aarch64:
    name: Build osx
    timeout-minutes: 30
    runs-on: macos-14
    steps:
      - name: Check architecture
        run: |
          uname -a
          find $(rustc --print sysroot) -name 'libstd-*.rlib' | sed -ne 's:^.*/\([^/]*\)/lib/libstd-[^/]*.rlib:\1:p'
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25.1'
      - name: Checkout code from repository
        uses: actions/checkout@v4
      - name: Build Base
        run: cargo build --release
      - name: Transform filenames
        run: mv target/release/proton-drive-bridge proton-drive-bridge
      - name: build archive
        run: |
            zip proton-drive-bridge-osx-aarch64.zip proton-drive-bridge users.json
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proton-drive-bridge-osx-aarch64
          path: proton-drive-bridge-osx-aarch64.zip
          retention-days: 5

  release:
    name: Release
    needs: [build-linux, build-windows, build-osx-aarch64]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            proton-drive-bridge-linux/*
            proton-drive-bridge-osx-aarch64/*
            proton-drive-bridge-windows/*
